dataset_path: /mnt/volumes/lpai-yharnam-vol-ga/lt/data/MME-VideoOCR
dataset_kwargs:
  token: True
test_split: train
task: mme_videoocr
output_type: generate_until
doc_to_visual: !function utils.mme_videoocr_doc_to_visual
doc_to_text: !function utils.mme_videoocr_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 512
  temperature: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.mme_videoocr_process_results
metric_list:
  - metric: overall_accuracy
    aggregation: !function utils.mme_videoocr_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metadata:
  - version: 0.0